# Generated by Django 5.0.6 on 2024-06-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookinfo_options_peopleinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name_plural': '人物信息'},
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='commetcount',
            new_name='commentcount',
        ),
    ]
